### ISSUE TITLE
Fix: navbar

### ISSUE THREAD

**Issue by mandartule** [Sahil-Sukhdeve12/PROJECT1-SPOTIFY-CLONE#1]
Nav bar is not till end 

![image](https://github.com/Sahil-Sukhdeve12/PROJECT1-SPOTIFY-CLONE/assets/105853152/d0c4bd58-a846-4c2f-aee9-13fad6b54bb6)

Steps to recreate :
1) go the webite 
2)watch the nav bar

fix #1

**Comment by Sahil-Sukhdeve12** [comment]
.
